# Setup
title:               Alistair Duffey
tagline:             'Climate science, solar geoengineering, the Arctic'
description:         'alistair.duffey.21 [at] ucl.ac.uk
                        <a href="https://twitter.com/alibduff" target="_blank">@alibduff</a>
                        <a href="https://scholar.google.com/citations?user=QHoneh4AAAAJ&hl=en" target="_blank">Google Scholar</a>'
url:                 http://alistairduffey.github.io
baseurl:             ''
paginate:            2
permalink:           pretty



# About/contact
author:
  name:              Alistair Duffey
  url:               https://twitter.com/alibduff
  email:             alistair.duffey.21@ucl.ac.uk

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
